"use client";

import { ChangeEvent, useMemo, useState } from "react";
import { jsPDF } from "jspdf";

type Item = { id: string; zone: string; nature: string; observation: string; analysis: string };
type Photo = { id: string; name: string; dataUrl: string; zone: string; caption: string; context: string; aiAnalysis: string; retained: boolean; loading: boolean };
type Chantier = Record<string, unknown>;
type Request = (path: string, options?: RequestInit) => Promise<any>; // eslint-disable-line @typescript-eslint/no-explicit-any
type Suggestion = { label: string; address: string; postalCode: string; city: string; lat: number; lng: number };

const blankItem = (): Item => ({ id: crypto.randomUUID(), zone: "", nature: "", observation: "", analysis: "" });
const initialMission = () => ({ reference: `EXP-${new Date().getFullYear()}-001`, title: "", chantier: "", expert: "", qualification: "", client: "", opposingParty: "", meetingAt: new Date().toISOString().slice(0, 16), purpose: "", documents: "", methodology: "Examen visuel des éléments accessibles et analyse des pièces communiquées.", conclusion: "", reservations: "", siteName: "", address: "", postalCode: "", city: "", latitude: "", longitude: "", building: "", floor: "", room: "", access: "", interventionZone: "" });

async function searchAddress(query: string): Promise<Suggestion[]> {
  const url = new URL("https://data.geopf.fr/geocodage/completion");
  url.searchParams.set("text", query); url.searchParams.set("maximumResponses", "6");
  const response = await fetch(url); if (!response.ok) throw new Error("Le service national des adresses est indisponible.");
  const payload = await response.json();
  return (payload.results ?? []).map((item: Record<string, unknown>) => ({ label: String(item.fulltext ?? ""), address: String(item.fulltext ?? "").split(",")[0], postalCode: String(item.zipcode ?? ""), city: String(item.city ?? ""), lat: Number(item.y ?? 0), lng: Number(item.x ?? 0) }));
}

async function imageForUpload(file: File) {
  const source = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
  const image = await new Promise<HTMLImageElement>((resolve, reject) => { const value = new Image(); value.onload = () => resolve(value); value.onerror = reject; value.src = source; });
  const scale = Math.min(1, 1600 / Math.max(image.width, image.height)); const canvas = document.createElement("canvas"); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale);
  canvas.getContext("2d")?.drawImage(image, 0, 0, canvas.width, canvas.height); return canvas.toDataURL("image/jpeg", .78);
}

export default function ExpertiseWorkspace({ chantiers, request }: { chantiers: Chantier[]; request: Request }) {
  const [step, setStep] = useState(1); const [validated, setValidated] = useState(false); const [message, setMessage] = useState("");
  const [items, setItems] = useState<Item[]>([blankItem()]); const [photos, setPhotos] = useState<Photo[]>([]); const [mission, setMission] = useState(initialMission());
  const [suggestions, setSuggestions] = useState<Suggestion[]>([]); const [aerial, setAerial] = useState(""); const [mapMessage, setMapMessage] = useState(""); const [consent, setConsent] = useState(false);
  const completeObservations = useMemo(() => items.filter((item) => item.observation.trim()), [items]);
  function invalidate() { setValidated(false); }
  function field(key: keyof typeof mission, value: string) { setMission((current) => ({ ...current, [key]: value })); invalidate(); }
  function updateItem(id: string, key: keyof Item, value: string) { setItems((current) => current.map((item) => item.id === id ? { ...item, [key]: value } : item)); invalidate(); }
  function updatePhoto(id: string, patch: Partial<Photo>) { setPhotos((current) => current.map((photo) => photo.id === id ? { ...photo, ...patch } : photo)); invalidate(); }

  async function onAddress(value: string) { field("address", value); setAerial(""); if (value.trim().length < 4) return setSuggestions([]); try { setSuggestions(await searchAddress(value)); } catch (error) { setMessage(error instanceof Error ? error.message : "Recherche impossible."); } }
  async function chooseAddress(value: Suggestion) {
    setMission((current) => ({ ...current, address: value.address, postalCode: value.postalCode, city: value.city, latitude: String(value.lat), longitude: String(value.lng) })); setSuggestions([]); invalidate(); setMapMessage("Chargement de la vue aérienne…");
    try { const result = await request("/parametres/expertise/vue-aerienne", { method: "POST", body: JSON.stringify({ latitude: value.lat, longitude: value.lng }) }); setAerial(result.image || ""); setMapMessage(result.configured ? "Vue aérienne Google Maps positionnée sur l’adresse." : result.message); } catch (error) { setMapMessage(error instanceof Error ? error.message : "Vue aérienne indisponible."); }
  }
  async function addPhotos(event: ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files ?? []).slice(0, Math.max(0, 12 - photos.length)); for (const file of files) { if (!/^image\/(jpeg|png|webp)$/.test(file.type)) continue; const dataUrl = await imageForUpload(file); setPhotos((current) => [...current, { id: crypto.randomUUID(), name: file.name, dataUrl, zone: mission.interventionZone, caption: "", context: "", aiAnalysis: "", retained: false, loading: false }]); } event.target.value = ""; invalidate(); }
  async function analysePhoto(photo: Photo) {
    if (!consent) return setMessage("Confirmez d’abord l’envoi ponctuel de la photo au service IA.");
    if (!photo.context.trim()) return setMessage("Ajoutez le contexte et les renseignements de l’expert avant l’analyse IA.");
    updatePhoto(photo.id, { loading: true });
    try { const result = await request("/parametres/expertise/photo/analyser", { method: "POST", body: JSON.stringify({ imageDataUrl: photo.dataUrl, context: photo.context, zone: photo.zone, location: [mission.floor, mission.room].filter(Boolean).join(" · ") }) }); updatePhoto(photo.id, { aiAnalysis: result.analysis, retained: false, loading: false }); setMessage("Analyse reçue comme aide à la lecture. Elle n’entre dans le rapport que si l’expert la retient."); } catch (error) { updatePhoto(photo.id, { loading: false }); setMessage(error instanceof Error ? error.message : "Analyse IA indisponible."); }
  }

  function validateReport() { if (!mission.title.trim() || !mission.expert.trim() || !mission.address.trim() || !completeObservations.length) return setMessage("Renseignez le titre, l’expert auteur, l’adresse et au moins une constatation factuelle."); setValidated(true); setMessage("Rapport validé par l’expert auteur. Toute modification le replacera en projet."); }
  function exportPdf() {
    if (!validated) return setMessage("L’expert doit valider explicitement le rapport avant son export définitif.");
    const pdf = new jsPDF(); let y = 18; const page = () => { pdf.addPage(); y = 18; }; const line = (text: string, bold = false, size = 10) => { pdf.setFont("helvetica", bold ? "bold" : "normal"); pdf.setFontSize(size); const wrapped = pdf.splitTextToSize(text || "—", 174); if (y + wrapped.length * 5 > 278) page(); pdf.text(wrapped, 18, y); y += wrapped.length * 5 + 3; };
    line("KRITIA EXPERTISE", true, 20); line("RAPPORT ET PORTFOLIO VALIDÉS PAR LE PROFESSIONNEL AUTEUR", true, 8); line(`${mission.reference} · ${mission.title}`, true, 14); line(`Lieu : ${mission.siteName || mission.building || "Site"} — ${mission.address}, ${mission.postalCode} ${mission.city}`); line(`Localisation précise : ${[mission.building, mission.floor, mission.room, mission.interventionZone].filter(Boolean).join(" · ")}`); line(`Expert auteur : ${mission.expert}${mission.qualification ? ` · ${mission.qualification}` : ""}`); line(`Réunion / constat : ${new Date(mission.meetingAt).toLocaleString("fr-FR")}`); line(`Mission : ${mission.purpose}`); if (aerial) { if (y > 170) page(); pdf.addImage(aerial, "PNG", 18, y, 174, 94); y += 100; line("Vue aérienne de repérage — Google Maps Platform", false, 8); }
    line("Constatations et analyses du professionnel", true, 12); completeObservations.forEach((item, index) => { line(`${index + 1}. ${item.nature || "Constatation"} — ${item.zone || "Zone non précisée"}`, true); line(`Fait observé : ${item.observation}`); if (item.analysis) line(`Analyse de l’expert : ${item.analysis}`); });
    if (photos.length) { page(); line("PORTFOLIO PHOTOGRAPHIQUE", true, 16); photos.forEach((photo, index) => { if (y > 175) page(); pdf.addImage(photo.dataUrl, "JPEG", 18, y, 82, 62); pdf.setFontSize(10); pdf.setFont("helvetica", "bold"); pdf.text(`Photo ${index + 1} · ${photo.zone || "Zone non précisée"}`, 105, y + 5); pdf.setFont("helvetica", "normal"); const caption = pdf.splitTextToSize(photo.caption || photo.context || photo.name, 85); pdf.text(caption, 105, y + 12); y += 68; if (photo.retained && photo.aiAnalysis) { line("Analyse IA relue et retenue par l’expert :", true, 9); line(photo.aiAnalysis, false, 9); } }); }
    line("Conclusion de l’expert", true, 12); line(mission.conclusion); if (mission.reservations) { line("Réserves et limites", true, 12); line(mission.reservations); } line("Déclaration", true, 11); line("Ce rapport a été renseigné et validé par le professionnel identifié. KRITIA structure et met en forme les données ; l’IA éventuelle fournit seulement des pistes. KRITIA n’est ni l’auteur de l’expertise ni le validateur de ses conclusions."); pdf.save(`${mission.reference || "rapport-expertise"}.pdf`);
  }

  return <div className="expertise-page">
    <section className="expertise-hero"><div><p className="eyebrow">KRITIA EXPERTISE</p><h2>Du lieu au rapport illustré.</h2><p>Adresse, repérage aérien, localisation intérieure, constatations et portfolio photo.</p></div><span className={validated ? "report-state validated" : "report-state"}>{validated ? "VALIDÉ PAR L’EXPERT" : "PROJET NON VALIDÉ"}</span></section>
    <nav className="expertise-steps" aria-label="Étapes du rapport">{["Mission & lieu", "Parties", "Constats & photos", "Rapport"].map((label, index) => <button key={label} className={step === index + 1 ? "active" : ""} onClick={() => setStep(index + 1)}><b>{index + 1}</b>{label}</button>)}</nav>
    {message && <div className="alert expertise-message">{message}<button onClick={() => setMessage("")}>×</button></div>}
    {step === 1 && <><section className="panel expertise-panel"><h3>Cadre de la mission</h3><div className="form-grid"><label>Référence<input value={mission.reference} onChange={(e) => field("reference", e.target.value)} /></label><label>Intitulé *<input value={mission.title} onChange={(e) => field("title", e.target.value)} placeholder="Ex. constat de désordres en façade" /></label><label>Dossier BTP lié<select value={mission.chantier} onChange={(e) => field("chantier", e.target.value)}><option value="">Aucun</option>{chantiers.map((item, i) => <option key={String(item.id ?? i)}>{String(item.reference ?? "")} · {String(item.objet ?? "Chantier")}</option>)}</select></label><label>Date de réunion<input type="datetime-local" value={mission.meetingAt} onChange={(e) => field("meetingAt", e.target.value)} /></label><label className="full">Objet de la mission<textarea rows={3} value={mission.purpose} onChange={(e) => field("purpose", e.target.value)} /></label></div></section>
      <section className="panel expertise-panel"><h3>Lieu de l’expertise</h3><div className="form-grid"><label>Nom du lieu<input value={mission.siteName} onChange={(e) => field("siteName", e.target.value)} placeholder="Résidence, immeuble, chantier…" /></label><label>Bâtiment / entrée<input value={mission.building} onChange={(e) => field("building", e.target.value)} placeholder="Bâtiment B, entrée cour…" /></label><label className="full address-field">Adresse *<input value={mission.address} onChange={(e) => void onAddress(e.target.value)} placeholder="17 avenue…" />{suggestions.length > 0 && <span className="expertise-address-list">{suggestions.map((item) => <button key={`${item.label}-${item.lat}`} onClick={() => void chooseAddress(item)}>{item.label}</button>)}</span>}</label><label>Code postal<input value={mission.postalCode} onChange={(e) => field("postalCode", e.target.value)} /></label><label>Ville<input value={mission.city} onChange={(e) => field("city", e.target.value)} /></label><label>Étage / niveau<input value={mission.floor} onChange={(e) => field("floor", e.target.value)} placeholder="R+2, sous-sol…" /></label><label>Pièce / local<input value={mission.room} onChange={(e) => field("room", e.target.value)} placeholder="Séjour, lot 12…" /></label><label>Zone d’intervention<input value={mission.interventionZone} onChange={(e) => field("interventionZone", e.target.value)} placeholder="Façade nord, toiture…" /></label><label>Accès et repères<input value={mission.access} onChange={(e) => field("access", e.target.value)} placeholder="Digicode, escalier gauche…" /></label></div>
      {(aerial || mapMessage) && <div className="aerial-card">{aerial ? <img src={aerial} alt="Vue aérienne du lieu de l’expertise" /> : <div className="aerial-placeholder">VUE AÉRIENNE À CONFIGURER</div>}<div><strong>{mapMessage}</strong>{mission.latitude && <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${mission.latitude},${mission.longitude}`}>Ouvrir le lieu dans Google Maps ↗</a>}</div></div>}</section></>}
    {step === 2 && <section className="panel expertise-panel"><h3>Auteur et parties</h3><div className="form-grid"><label>Expert auteur *<input value={mission.expert} onChange={(e) => field("expert", e.target.value)} /></label><label>Qualification / spécialité<input value={mission.qualification} onChange={(e) => field("qualification", e.target.value)} /></label><label>Demandeur<input value={mission.client} onChange={(e) => field("client", e.target.value)} /></label><label>Autre partie / représentant<input value={mission.opposingParty} onChange={(e) => field("opposingParty", e.target.value)} /></label><label className="full">Documents communiqués<textarea rows={5} value={mission.documents} onChange={(e) => field("documents", e.target.value)} /></label></div></section>}
    {step === 3 && <section className="expertise-observations"><div className="panel-title"><div><h3>Constatations et portfolio</h3><p>Les faits restent séparés des interprétations et des pistes IA.</p></div><button className="primary compact" onClick={() => setItems([...items, blankItem()])}>＋ Constat</button></div>{items.map((item, index) => <article className="panel observation-card" key={item.id}><header><strong>Constatation {index + 1}</strong>{items.length > 1 && <button onClick={() => setItems(items.filter((candidate) => candidate.id !== item.id))}>Supprimer</button>}</header><div className="form-grid"><label>Zone / ouvrage<input value={item.zone} onChange={(e) => updateItem(item.id, "zone", e.target.value)} /></label><label>Nature<input value={item.nature} onChange={(e) => updateItem(item.id, "nature", e.target.value)} /></label><label className="full">Faits visibles *<textarea rows={3} value={item.observation} onChange={(e) => updateItem(item.id, "observation", e.target.value)} /></label><label className="full">Analyse rédigée par l’expert<textarea rows={3} value={item.analysis} onChange={(e) => updateItem(item.id, "analysis", e.target.value)} /></label></div></article>)}
      <section className="panel photo-portfolio"><div className="panel-title"><div><h3>Portfolio photographique</h3><p>JPEG, PNG ou WebP · 12 photos maximum dans cette première version.</p></div><label className="primary compact upload-button">＋ Ajouter des photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(e) => void addPhotos(e)} /></label></div><label className="ai-consent"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} /> J’autorise l’envoi ponctuel de la photo sélectionnée au service OpenAI pour obtenir une aide à l’analyse. KRITIA ne l’enregistre pas côté serveur dans ce flux.</label><div className="photo-grid">{photos.map((photo) => <article key={photo.id} className="photo-card"><img src={photo.dataUrl} alt={photo.caption || photo.name} /><button className="photo-remove" onClick={() => setPhotos(photos.filter((item) => item.id !== photo.id))}>×</button><label>Zone<input value={photo.zone} onChange={(e) => updatePhoto(photo.id, { zone: e.target.value })} /></label><label>Légende du portfolio<textarea rows={2} value={photo.caption} onChange={(e) => updatePhoto(photo.id, { caption: e.target.value })} /></label><label>Contexte communiqué à l’IA<textarea rows={3} value={photo.context} onChange={(e) => updatePhoto(photo.id, { context: e.target.value })} placeholder="Ce que vous constatez, historique connu, mesures déjà faites…" /></label><button className="secondary" disabled={photo.loading} onClick={() => void analysePhoto(photo)}>{photo.loading ? "Analyse en cours…" : "Analyser avec l’IA"}</button>{photo.aiAnalysis && <div className="ai-photo-result"><strong>Proposition IA — non retenue par défaut</strong><p>{photo.aiAnalysis}</p><label><input type="checkbox" checked={photo.retained} onChange={(e) => updatePhoto(photo.id, { retained: e.target.checked })} /> Relue et retenue par l’expert dans le rapport</label></div>}</article>)}</div></section></section>}
    {step === 4 && <section className="panel expertise-panel"><h3>Analyse et validation finale</h3><div className="report-summary"><span>{completeObservations.length} constatation(s)</span><span>{photos.length} photo(s)</span><span>{photos.filter((p) => p.retained).length} analyse(s) IA retenue(s)</span></div><div className="form-grid"><label className="full">Méthodologie<textarea rows={3} value={mission.methodology} onChange={(e) => field("methodology", e.target.value)} /></label><label className="full">Conclusion de l’expert<textarea rows={7} value={mission.conclusion} onChange={(e) => field("conclusion", e.target.value)} /></label><label className="full">Réserves et limites<textarea rows={4} value={mission.reservations} onChange={(e) => field("reservations", e.target.value)} /></label></div><div className="expertise-declaration"><strong>Responsabilité éditoriale</strong><p>KRITIA structure les informations et l’IA suggère des points d’attention. Le professionnel reste seul auteur et responsable des constatations, analyses, conclusions et préconisations qu’il valide.</p></div><div className="expertise-actions"><button className="secondary" onClick={() => setMessage("Projet conservé uniquement dans cette session : la persistance sécurisée du dossier reste à développer.")}>Conserver comme projet</button><button className="primary" onClick={validateReport}>Valider comme expert auteur</button><button className="primary" disabled={!validated} onClick={exportPdf}>Télécharger rapport + portfolio</button></div></section>}
    <div className="step-navigation"><button className="secondary compact" disabled={step === 1} onClick={() => setStep(step - 1)}>← Précédent</button><button className="primary compact" disabled={step === 4} onClick={() => setStep(step + 1)}>Suivant →</button></div>
  </div>;
}
